version: '3.8'
services:
  app:
    build: .
    image: 192.168.33.10:8083/nodemongoapp:6.0
    restart: always
    container_name: back
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: mongodb+srv://yosrcharek:yosrcharek@cluster0.0n8kr.mongodb.net/smart190
    volumes:
      - .:/app
